# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build_and_test:
    docker:
      — image: cimg/node:18.8.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests
      - run:
          command: npm run build
          name: Build app

workflows:
  build_and_test:
    jobs:
      - build_and_test
