# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install:
          node-version: '16.15'
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app
      - run:
          command: npm run lint
          name: Check Lint
      - run:
          command: npm test
          name: Run tests
workflows:
  run:
    jobs:
      - build_and_test
